### ISSUE TITLE
Reference TV reconstruction for ellipse data

### ISSUE THREAD

**Issue by ChengV0** [adler-j/learned_primal_dual#3]
when i run reference_tv_shepp.py,
![image](https://user-images.githubusercontent.com/34834140/49772737-4fda6780-fd29-11e8-8e91-d8ed8a095c3c.png)
![image](https://user-images.githubusercontent.com/34834140/49772778-739dad80-fd29-11e8-9f2f-e472514d1c46.png)
![image](https://user-images.githubusercontent.com/34834140/49772798-7c8e7f00-fd29-11e8-8810-8b1a1b21ed9a.png)
![image](https://user-images.githubusercontent.com/34834140/49772860-b3649500-fd29-11e8-85e8-8d4f2c0a93bc.png)
Thanks for your reply.

**Comment by AceCoooool** [comment]
You can change the position of g and f in `odl.solvers.pdhg`. (However, the results is worst than paper)

**Comment by ChengV0** [comment]
> You can change the position of g and f in `odl.solvers.pdhg`. (However, the results is worst than paper)

thanks for your reply ,i will try it later.

**Comment by adler-j** [comment]
This is due to a standardization of parameters in ODL, I have a bugfix coming. The correct fix should be to rename g <-> f, if you just change the order then the steps etc are wrong. I though I had uploaded this but it seems I didn't.

**Comment by ChengV0** [comment]
> This is due to a standardization of parameters in ODL, I have a bugfix coming. The correct fix should be to rename g <-> f, if you just change the order then the steps etc are wrong. I though I had uploaded this but it seems I didn't.

thanks for your ad

> > You can change the position of g and f in `odl.solvers.pdhg`. (However, the results is worst than paper)
> 
> thanks for your reply ,i will try it later.

![image](https://user-images.githubusercontent.com/34834140/50149989-a6324200-02f7-11e9-92be-38536885a983.png)
this is the result after change the position of g and f.

**Comment by ChengV0** [comment]
> This is due to a standardization of parameters in ODL, I have a bugfix coming. The correct fix should be to rename g <-> f, if you just change the order then the steps etc are wrong. I though I had uploaded this but it seems I didn't.
thanks for your advice,i will try it later.

**Comment by adler-j** [comment]
23,5 sounds very wrong. I'll have to look into that.

**Comment by ChengV0** [comment]
> 23,5 sounds very wrong. I'll have to look into that.

Okay,waiting for your results

**Comment by ChengV0** [comment]
> 23,5 sounds very wrong. I'll have to look into that.

Dear Adler, how about the result?

**Comment by 99991** [comment]
I am also interested. I think this issue should be reopened.
